apiVersion: federatorai.containers.ai/v1alpha1
kind: AlamedaService
metadata:
  name: my-alamedaservice
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "3000"
spec:
  keycode:
    codeNumber: GRV7J-LA4TX-KPPIT-S6GRS-NK4EB-ILFRQ
  selfDriving: false            ## to enable resource self-orchestration of the deployed Alameda components
                                ## it is recommended NOT to use ephemeral data storage for Alameda influxdb component when self-Driving is enabled
  enableExecution: true
  enableGui: true
  version: {{ .Values.alameda.version }}
{{ if .Values.prometheus.enabled }}
  prometheusService: http://prometheus-operated.{{ .Release.Namespace }}.svc:9090
{{ else }}
  prometheusService: {{ .Values.alameda.prometheusService }}
{{ end }}
  storages:                     ## see following details for where it is used in each component
    - usage: log                ## storage setting for log
      type: ephemeral           ## ephemeral means emptyDir{}
    - usage: data
      type: ephemeral
#    - usage: data               ## storage setting for data
#      type: pvc                 ## pvc means PersistentVolumeClaim
#      size: 10Gi                ## mandatory when type=pvc
#      class: "normal"           ## mandatory when type=pvc
  serviceExposures:
{{ if .Values.grafana.nodePort }}
  - name: alameda-grafana
    type: NodePort
    nodePort:
      ports:
      - port: 3001
        nodePort: {{ .Values.grafana.nodePort }}
{{ end }}
{{ if .Values.federatorai_rest.nodePort }}
  - name: federatorai-rest
    type: NodePort
    nodePort:
      ports:
      - port: 5056
        nodePort: {{ .Values.federatorai_rest.nodePort }}
{{ end }}
